replicaCount: 1

image:
  repository: hanumath/n8n-task
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 9001
  targetPort: 9001
  nodePort: 31001

containerPort: 9001

resources: {}

